management/urls.py
from django.conf.urls import url
from django.urls import re_path

from management.views import AssignmentListView, UserListView, DeviceListView, UserDeviceListView, SearchResultsView, \
    DeviceDetailView, UserDetailView, UserCreateView, DeviceCreateView, TeamCreateView, BuyerCreateView, \
    DeviceTypeCreateView, AssignmentCreateView, UserUpdateView, DeviceUpdateView, BuyerUpdateView, AssignmentUpdateView, \
    TeamUpdateView, DeviceTypeUpdateView, UserDeleteView, AssignmentDeleteView, DeviceDeleteView, TeamDeleteView, \
    DeviceTypeDeleteView, BuyerDeleteView, TeamListView, BuyerListView, DeviceTypeListView

app_name = 'management'

urlpatterns = (
    re_path(r'^$', AssignmentListView.as_view(), name='assignment_list'),
    url(r'user_list$', UserListView.as_view(), name='user_list'),
    url(r'user_devices_list/(?P<pk>[0-9]+)/$', UserDeviceListView.as_view(), name='user_devices_list'),
    url(r'device_list$', DeviceListView.as_view(), name='device_list'),
    url(r'team_list$', TeamListView.as_view(), name='team_list'),
    url(r'buyer_list$', BuyerListView.as_view(), name='buyer_list'),
    url(r'devicetype_list$', DeviceTypeListView.as_view(), name='devicetype_list'),

    url(r'user_detail/(?P<pk>[0-9]+)/$', UserDetailView.as_view(), name='user_detail'),
    url(r'device_detail/(?P<pk>[0-9]+)/$', DeviceDetailView.as_view(), name='device_detail'),

    url(r'user_create$', UserCreateView.as_view(), name='user_create'),
    url(r'device_create$', DeviceCreateView.as_view(), name='device_create'),
    url(r'team_create$', TeamCreateView.as_view(), name='team_create'),
    url(r'buyer_create$', BuyerCreateView.as_view(), name='buyer_create'),
    url(r'devicetype_create$', DeviceTypeCreateView.as_view(), name='devicetype_create'),
    url(r'assignment_create$', AssignmentCreateView.as_view(), name='assignment_create'),

    url(r'user_update/(?P<pk>[0-9]+)/$', UserUpdateView.as_view(), name='user_update'),
    url(r'device_update/(?P<pk>[0-9]+)/$', DeviceUpdateView.as_view(), name='device_update'),
    url(r'team_update/(?P<pk>[0-9]+)/$', TeamUpdateView.as_view(), name='team_update'),
    url(r'buyer_update/(?P<pk>[0-9]+)/$', BuyerUpdateView.as_view(), name='buyer_update'),
    url(r'devicetype_update/(?P<pk>[0-9]+)/$', DeviceTypeUpdateView.as_view(), name='devicetype_update'),
    url(r'assignment_update/(?P<pk>[0-9]+)/$', AssignmentUpdateView.as_view(), name='assignment_update'),

    url(r'user_delete/(?P<pk>[0-9]+)/$', UserDeleteView.as_view(success_url="management:user_list"),
        name='user_delete'),
    url(r'device_delete/(?P<pk>[0-9]+)/$', DeviceDeleteView.as_view(success_url="management:device_list"),
        name='device_delete'),
    url(r'team_delete/(?P<pk>[0-9]+)/$', TeamDeleteView.as_view(success_url="management:team_list"),
        name='team_delete'),
    url(r'buyer_delete/(?P<pk>[0-9]+)/$', BuyerDeleteView.as_view(success_url="management:buyer_list"),
        name='buyer_delete'),
    url(r'devicetype_delete/(?P<pk>[0-9]+)/$', DeviceTypeDeleteView.as_view(success_url="management:devicetype_list"),
        name='devicetype_delete'),
    url(r'assignment_delete/(?P<pk>[0-9]+)/$', AssignmentDeleteView.as_view(success_url="/"), name='assignment_delete'),

    url(r'search_results$', SearchResultsView.as_view(), name='search_results'),
)

management/models.py
from django.db import models
from django.urls import reverse


class User(models.Model):
    first_name = models.CharField('First Name', max_length=50)
    last_name = models.CharField('Last Name', max_length=50)
    user_photo = models.ImageField('User Photo', upload_to='user_photos/')
    employee_date = models.DateField('Employee date', auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_absolute_url(self):
        return reverse('management:user_detail', args=[self.id])

    def get_user_devices_list(self):
        return reverse('management:user_devices_list', args=[self.id])

class Buyer(models.Model):
    buyer_name = models.CharField('Buyer Name', max_length=50, unique=True)

    def __str__(self):
        return self.buyer_name

    @staticmethod
    def get_absolute_url():
        return reverse('management:buyer_list')


class Team(models.Model):
    team_name = models.CharField('Team Name', max_length=50, unique=True)

    def __str__(self):
        return self.team_name

    @staticmethod
    def get_absolute_url():
        return reverse('management:team_list')


class DeviceType(models.Model):
    device_type = models.CharField('Device type', max_length=50, unique=True)

    def __str__(self):
        return self.device_type

    @staticmethod
    def get_absolute_url():
        return reverse('management:devicetype_list')


class Device(models.Model):
    item_number = models.AutoField('Item number', primary_key=True)
    device_name = models.CharField('Device Name', max_length=50)
    price = models.IntegerField('Price')
    purchase_date = models.DateField('Purchase_date', auto_now=True)
    paid_by = models.ForeignKey(Buyer, on_delete=models.PROTECT)
    team = models.ForeignKey(Team, on_delete=models.PROTECT)
    configuration = models.URLField('URL for configuration')
    device_photo = models.ImageField('Device Photo', upload_to='device_photos/')
    device_type = models.ForeignKey(DeviceType, on_delete=models.PROTECT)

    def __str__(self):
        return self.device_name

    def get_absolute_url(self):
        return reverse('management:device_detail', args=[self.item_number])

    def is_busy(self):
        check = Assignment.objects.filter(device_id=self.item_number)
        return check


class Assignment(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    device = models.OneToOneField(Device, on_delete=models.PROTECT)
    comment = models.TextField('Comment')
    assignment_date = models.DateField('Assignment date', editable=True, auto_now_add=True)

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

    @staticmethod
    def get_absolute_url():
        return reverse('management:assignment_list')

management/forms.py
from django.forms import ModelForm

from management.models import Assignment, User, Device, Team


class AssignmentForm(ModelForm):
    class Meta:
        model = Assignment
        fields = ['user', 'device', 'assignment_date', 'comment']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'user_photo']


class DeviceForm(ModelForm):
    class Meta:
        model = Device
        fields = ['device_name', 'price', 'paid_by', 'team', 'configuration', 'device_type', 'device_photo']


class TeamForm(ModelForm):
    class Meta:
        model = Team
        fields = ['team_name']


class BuyerForm(ModelForm):
    class Meta:
        model = Team
        fields = ['buyer_name']

management/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Q, ProtectedError
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView

from management.models import Assignment, User, Device, Team, Buyer, DeviceType


# Create Views
class UserCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'polls.can_add'
    model = User
    fields = ['first_name', 'last_name', 'user_photo']
    template_name = 'management/user/user_create.html'


class DeviceTypeCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'polls.can_add'
    model = DeviceType
    fields = ['device_type']
    template_name = 'management/device/devicetype_create.html'


class TeamCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'polls.can_add'
    model = Team
    fields = ['team_name']
    template_name = 'management/team/team_create.html'


class BuyerCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'polls.can_add'
    model = Buyer
    fields = ['buyer_name']
    template_name = 'management/buyer/buyer_create.html'


class DeviceCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'polls.can_add'
    model = Device
    fields = ['device_name', 'price', 'paid_by', 'team', 'configuration', 'device_type', 'device_photo']
    template_name = 'management/device/device_create.html'


class AssignmentCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'polls.can_add'
    model = Assignment
    fields = ['user', 'device', 'comment']
    template_name = 'management/assignment/assignment_create.html'


# Update Views
class AssignmentUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'polls.can_edit'
    model = Assignment
    fields = ['user', 'device', 'comment']
    template_name = 'management/assignment/assignment_create.html'


class BuyerUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'polls.can_add'
    model = Buyer
    fields = ['buyer_name']
    template_name = 'management/buyer/buyer_create.html'


class UserUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'polls.can_add'
    model = User
    fields = ['first_name', 'last_name', 'user_photo']
    template_name = 'management/user/user_create.html'


class DeviceUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'polls.can_add'
    model = Device
    fields = ['device_name', 'price', 'paid_by', 'team', 'configuration', 'device_type', 'device_photo']
    template_name = 'management/device/device_create.html'


class TeamUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'polls.can_add'
    model = Team
    fields = ['team_name']
    template_name = 'management/team/team_create.html'


class DeviceTypeUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'polls.can_add'
    model = DeviceType
    fields = ['device_type']
    template_name = 'management/device/devicetype_create.html'


# Delete Views
class AssignmentDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'polls.can_delete'
    model = Assignment
    template_name = 'management/confirm_delete.html'


class UserDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'polls.can_delete'
    model = User
    template_name = 'management/confirm_delete.html'

    def post(self, request, *args, **kwargs):
        try:
            return self.delete(request, *args, **kwargs)
        except ProtectedError:
            return render(request, 'management/confirm_delete.html', {'Protected_Error': 'Protected_Error'})


class DeviceDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'polls.can_delete'
    model = Device
    template_name = 'management/confirm_delete.html'

    def post(self, request, *args, **kwargs):
        try:
            return self.delete(request, *args, **kwargs)
        except ProtectedError:
            return render(request, 'management/confirm_delete.html', {'Protected_Error': 'Protected_Error'})


class TeamDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'polls.can_delete'
    model = Team
    template_name = 'management/confirm_delete.html'

    def post(self, request, *args, **kwargs):
        try:
            return self.delete(request, *args, **kwargs)
        except ProtectedError:
            return render(request, 'management/confirm_delete.html', {'Protected_Error': 'Protected_Error'})


class DeviceTypeDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'polls.can_delete'
    model = DeviceType
    template_name = 'management/confirm_delete.html'

    def post(self, request, *args, **kwargs):
        try:
            return self.delete(request, *args, **kwargs)
        except ProtectedError:
            return render(request, 'management/confirm_delete.html', {'Protected_Error': 'Protected_Error'})


class BuyerDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'polls.can_delete'
    model = Buyer
    template_name = 'management/confirm_delete.html'

    def post(self, request, *args, **kwargs):
        try:
            return self.delete(request, *args, **kwargs)
        except ProtectedError:
            return render(request, 'management/confirm_delete.html', {'Protected_Error': 'Protected_Error'})


# List Views
class AssignmentListView(ListView):
    model = Assignment
    context_object_name = 'assignment_list_data'
    queryset = Assignment.objects.order_by('assignment_date')
    template_name = 'management/assignment/assignment_list.html'


class UserListView(ListView):
    model = User
    context_object_name = 'user_list_data'
    queryset = User.objects.order_by('employee_date')
    template_name = 'management/user/user_list.html'


class UserDeviceListView(ListView):
    model = Assignment
    context_object_name = 'user_devices'
    template_name = 'management/user/user_device_list.html'

    def get_queryset(self):
        return Assignment.objects.filter(user_id=self.kwargs['pk'])


class DeviceListView(ListView):
    model = Device
    context_object_name = 'device_list'
    queryset = Device.objects.order_by('purchase_date')
    template_name = 'management/device/device_list.html'


class TeamListView(ListView):
    model = Team
    context_object_name = 'team_list'
    template_name = 'management/team/team_list.html'


class BuyerListView(ListView):
    model = Buyer
    context_object_name = 'buyer_list'
    template_name = 'management/buyer/buyer_list.html'


class DeviceTypeListView(ListView):
    model = DeviceType
    context_object_name = 'devicetype_list'
    template_name = 'management/device/devicetype_list.html'


# Detail Views
class UserDetailView(DetailView):
    model = User
    context_object_name = 'user_detail'
    template_name = 'management/user/user_detail.html'


class DeviceDetailView(DetailView):
    model = Device
    context_object_name = 'device_detail'
    template_name = 'management/device/device_detail.html'


# Search Views
class SearchResultsView(ListView):
    model = Device
    template_name = 'management/device/device_list.html'
    context_object_name = 'device_list'

    def get_queryset(self):  # новый
        query = self.request.GET.get('q')
        object_list = Device.objects.filter(
            Q(device_name__icontains=query) | Q(device_name__icontains=query)
        )
        return object_list

templates/management/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/journal/bootstrap.min.css" integrity="sha384-QDSPDoVOoSWz2ypaRUidLmLYl4RyoBWI44iA5agn6jHegBxZkNqgm2eHb6yZ5bYs" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js" integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>

</head>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{% url 'management:assignment_list' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'management:user_list' %}">User list <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'management:device_list' %}">Device list</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'management:team_list' %}">Team list</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'management:buyer_list' %}">Buyer list</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'management:devicetype_list' %}">Device type list</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/api/">API</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Options</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'management:user_create' %}">Create user</a>
                    <a class="dropdown-item" href="{% url 'management:device_create' %}">Create device</a>
                    <a class="dropdown-item" href="{% url 'management:team_create' %}">Create team</a>
                    <a class="dropdown-item" href="{% url 'management:buyer_create' %}">Create buyer</a>
                    <a class="dropdown-item" href="{% url 'management:devicetype_create' %}">Create device type</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'management:assignment_create' %}">Сreate distribution</a>
                </div>
            </li>
            {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'management:search_results' %}" method="get">
            <input class="form-control mr-sm-2" name="q" type="text" placeholder="Search device">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
        {% if request.user.is_authenticated %}
            <a style="color: black" class="btn btn-danger" href="/admin/logout/">Выйти</a>
        {% else %}
            <a style="color: black" class="btn btn-success" href="/admin/login/">Войти</a>
        {% endif %}
    </div>
</nav>
<body>
{% block body %}{% endblock %}
</body>
</html>

templates/management/confirm_delete.html
{% extends 'management/base.html' %}

{% block body %}
<form method="post">
    {% csrf_token %}
    <div class="container">
    <div class="bg-light my-4 p-4 text-center">
        {% if Protected_Error %}
        <p>Protected Error</p>
        {% else %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm"/>
        {% endif %}
    </div>
    </div>>
</form>

{% endblock %}