management/urls.py
from django.conf.urls import url
from django.urls import re_path

from management.views import AssignmentListView, UserListView, DeviceListView, UserDeviceListView, SearchResultsView, \
    DeviceDetailView, UserDetailView, UserCreateView, DeviceCreateView, TeamCreateView, BuyerCreateView, \
    DeviceTypeCreateView, AssignmentCreateView, UserUpdateView, DeviceUpdateView, BuyerUpdateView, AssignmentUpdateView, \
    TeamUpdateView, DeviceTypeUpdateView, UserDeleteView, AssignmentDeleteView, DeviceDeleteView, TeamDeleteView, \
    DeviceTypeDeleteView, BuyerDeleteView, TeamListView, BuyerListView, DeviceTypeListView

app_name = 'management'

urlpatterns = (
    re_path(r'^$', AssignmentListView.as_view(), name='assignment_list'),
    url(r'user_list$', UserListView.as_view(), name='user_list'),
    url(r'user_devices_list/(?P<pk>[0-9]+)/$', UserDeviceListView.as_view(), name='user_devices_list'),
    url(r'device_list$', DeviceListView.as_view(), name='device_list'),
    url(r'team_list$', TeamListView.as_view(), name='team_list'),
    url(r'buyer_list$', BuyerListView.as_view(), name='buyer_list'),
    url(r'devicetype_list$', DeviceTypeListView.as_view(), name='devicetype_list'),

    url(r'user_detail/(?P<pk>[0-9]+)/$', UserDetailView.as_view(), name='user_detail'),
    url(r'device_detail/(?P<pk>[0-9]+)/$', DeviceDetailView.as_view(), name='device_detail'),

    url(r'user_create$', UserCreateView.as_view(), name='user_create'),
    url(r'device_create$', DeviceCreateView.as_view(), name='device_create'),
    url(r'team_create$', TeamCreateView.as_view(), name='team_create'),
    url(r'buyer_create$', BuyerCreateView.as_view(), name='buyer_create'),
    url(r'devicetype_create$', DeviceTypeCreateView.as_view(), name='devicetype_create'),
    url(r'assignment_create$', AssignmentCreateView.as_view(), name='assignment_create'),

    url(r'user_update/(?P<pk>[0-9]+)/$', UserUpdateView.as_view(), name='user_update'),
    url(r'device_update/(?P<pk>[0-9]+)/$', DeviceUpdateView.as_view(), name='device_update'),
    url(r'team_update/(?P<pk>[0-9]+)/$', TeamUpdateView.as_view(), name='team_update'),
    url(r'buyer_update/(?P<pk>[0-9]+)/$', BuyerUpdateView.as_view(), name='buyer_update'),
    url(r'devicetype_update/(?P<pk>[0-9]+)/$', DeviceTypeUpdateView.as_view(), name='devicetype_update'),
    url(r'assignment_update/(?P<pk>[0-9]+)/$', AssignmentUpdateView.as_view(), name='assignment_update'),

    url(r'user_delete/(?P<pk>[0-9]+)/$', UserDeleteView.as_view(success_url="management:user_list"),
        name='user_delete'),
    url(r'device_delete/(?P<pk>[0-9]+)/$', DeviceDeleteView.as_view(success_url="management:device_list"),
        name='device_delete'),
    url(r'team_delete/(?P<pk>[0-9]+)/$', TeamDeleteView.as_view(success_url="management:team_list"),
        name='team_delete'),
    url(r'buyer_delete/(?P<pk>[0-9]+)/$', BuyerDeleteView.as_view(success_url="management:buyer_list"),
        name='buyer_delete'),
    url(r'devicetype_delete/(?P<pk>[0-9]+)/$', DeviceTypeDeleteView.as_view(success_url="management:devicetype_list"),
        name='devicetype_delete'),
    url(r'assignment_delete/(?P<pk>[0-9]+)/$', AssignmentDeleteView.as_view(success_url="/"), name='assignment_delete'),

    url(r'search_results$', SearchResultsView.as_view(), name='search_results'),
)

management/models.py
from django.db import models
from django.urls import reverse


class User(models.Model):
    first_name = models.CharField('First Name', max_length=50)
    last_name = models.CharField('Last Name', max_length=50)
    user_photo = models.ImageField('User Photo', upload_to='user_photos/')
    employee_date = models.DateField('Employee date', auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_absolute_url(self):
        return reverse('management:user_detail', args=[self.id])

    def get_user_devices_list(self):
        return reverse('management:user_devices_list', args=[self.id])

class Buyer(models.Model):
    buyer_name = models.CharField('Buyer Name', max_length=50, unique=True)

    def __str__(self):
        return self.buyer_name

    @staticmethod
    def get_absolute_url():
        return reverse('management:buyer_list')


class Team(models.Model):
    team_name = models.CharField('Team Name', max_length=50, unique=True)

    def __str__(self):
        return self.team_name

    @staticmethod
    def get_absolute_url():
        return reverse('management:team_list')


class DeviceType(models.Model):
    device_type = models.CharField('Device type', max_length=50, unique=True)

    def __str__(self):
        return self.device_type

    @staticmethod
    def get_absolute_url():
        return reverse('management:devicetype_list')


class Device(models.Model):
    item_number = models.AutoField('Item number', primary_key=True)
    device_name = models.CharField('Device Name', max_length=50)
    price = models.IntegerField('Price')
    purchase_date = models.DateField('Purchase_date', auto_now=True)
    paid_by = models.ForeignKey(Buyer, on_delete=models.PROTECT)
    team = models.ForeignKey(Team, on_delete=models.PROTECT)
    configuration = models.URLField('URL for configuration')
    device_photo = models.ImageField('Device Photo', upload_to='device_photos/')
    device_type = models.ForeignKey(DeviceType, on_delete=models.PROTECT)

    def __str__(self):
        return self.device_name

    def get_absolute_url(self):
        return reverse('management:device_detail', args=[self.item_number])

    def is_busy(self):
        check = Assignment.objects.filter(device_id=self.item_number)
        return check


class Assignment(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    device = models.OneToOneField(Device, on_delete=models.PROTECT)
    comment = models.TextField('Comment')
    assignment_date = models.DateField('Assignment date', editable=True, auto_now_add=True)

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

    @staticmethod
    def get_absolute_url():
        return reverse('management:assignment_list')

management/forms.py
from django.forms import ModelForm

from management.models import Assignment, User, Device, Team


class AssignmentForm(ModelForm):
    class Meta:
        model = Assignment
        fields = ['user', 'device', 'assignment_date', 'comment']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'user_photo']


class DeviceForm(ModelForm):
    class Meta:
        model = Device
        fields = ['device_name', 'price', 'paid_by', 'team', 'configuration', 'device_type', 'device_photo']


class TeamForm(ModelForm):
    class Meta:
        model = Team
        fields = ['team_name']


class BuyerForm(ModelForm):
    class Meta:
        model = Team
        fields = ['buyer_name']

management/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Q, ProtectedError
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView

from management.models import Assignment, User, Device, Team, Buyer, DeviceType


# Create Views
class UserCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'polls.can_add'
    model = User
    fields = ['first_name', 'last_name', 'user_photo']
    template_name = 'management/user/user_create.html'


class DeviceTypeCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'polls.can_add'
    model = DeviceType
    fields = ['device_type']
    template_name = 'management/device/devicetype_create.html'


class TeamCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'polls.can_add'
    model = Team
    fields = ['team_name']
    template_name = 'management/team/team_create.html'


class BuyerCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'polls.can_add'
    model = Buyer
    fields = ['buyer_name']
    template_name = 'management/buyer/buyer_create.html'


class DeviceCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'polls.can_add'
    model = Device
    fields = ['device_name', 'price', 'paid_by', 'team', 'configuration', 'device_type', 'device_photo']
    template_name = 'management/device/device_create.html'


class AssignmentCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'polls.can_add'
    model = Assignment
    fields = ['user', 'device', 'comment']
    template_name = 'management/assignment/assignment_create.html'


# Update Views
class AssignmentUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'polls.can_edit'
    model = Assignment
    fields = ['user', 'device', 'comment']
    template_name = 'management/assignment/assignment_create.html'


class BuyerUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'polls.can_add'
    model = Buyer
    fields = ['buyer_name']
    template_name = 'management/buyer/buyer_create.html'


class UserUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'polls.can_add'
    model = User
    fields = ['first_name', 'last_name', 'user_photo']
    template_name = 'management/user/user_create.html'


class DeviceUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'polls.can_add'
    model = Device
    fields = ['device_name', 'price', 'paid_by', 'team', 'configuration', 'device_type', 'device_photo']
    template_name = 'management/device/device_create.html'


class TeamUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'polls.can_add'
    model = Team
    fields = ['team_name']
    template_name = 'management/team/team_create.html'


class DeviceTypeUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'polls.can_add'
    model = DeviceType
    fields = ['device_type']
    template_name = 'management/device/devicetype_create.html'


# Delete Views
class AssignmentDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'polls.can_delete'
    model = Assignment
    template_name = 'management/confirm_delete.html'


class UserDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'polls.can_delete'
    model = User
    template_name = 'management/confirm_delete.html'

    def post(self, request, *args, **kwargs):
        try:
            return self.delete(request, *args, **kwargs)
        except ProtectedError:
            return render(request, 'management/confirm_delete.html', {'Protected_Error': 'Protected_Error'})


class DeviceDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'polls.can_delete'
    model = Device
    template_name = 'management/confirm_delete.html'

    def post(self, request, *args, **kwargs):
        try:
            return self.delete(request, *args, **kwargs)
        except ProtectedError:
            return render(request, 'management/confirm_delete.html', {'Protected_Error': 'Protected_Error'})


class TeamDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'polls.can_delete'
    model = Team
    template_name = 'management/confirm_delete.html'

    def post(self, request, *args, **kwargs):
        try:
            return self.delete(request, *args, **kwargs)
        except ProtectedError:
            return render(request, 'management/confirm_delete.html', {'Protected_Error': 'Protected_Error'})


class DeviceTypeDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'polls.can_delete'
    model = DeviceType
    template_name = 'management/confirm_delete.html'

    def post(self, request, *args, **kwargs):
        try:
            return self.delete(request, *args, **kwargs)
        except ProtectedError:
            return render(request, 'management/confirm_delete.html', {'Protected_Error': 'Protected_Error'})


class BuyerDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'polls.can_delete'
    model = Buyer
    template_name = 'management/confirm_delete.html'

    def post(self, request, *args, **kwargs):
        try:
            return self.delete(request, *args, **kwargs)
        except ProtectedError:
            return render(request, 'management/confirm_delete.html', {'Protected_Error': 'Protected_Error'})


# List Views
class AssignmentListView(ListView):
    model = Assignment
    context_object_name = 'assignment_list_data'
    queryset = Assignment.objects.order_by('assignment_date')
    template_name = 'management/assignment/assignment_list.html'


class UserListView(ListView):
    model = User
    context_object_name = 'user_list_data'
    queryset = User.objects.order_by('employee_date')
    template_name = 'management/user/user_list.html'


class UserDeviceListView(ListView):
    model = Assignment
    context_object_name = 'user_devices'
    template_name = 'management/user/user_device_list.html'

    def get_queryset(self):
        return Assignment.objects.filter(user_id=self.kwargs['pk'])


class DeviceListView(ListView):
    model = Device
    context_object_name = 'device_list'
    queryset = Device.objects.order_by('purchase_date')
    template_name = 'management/device/device_list.html'


class TeamListView(ListView):
    model = Team
    context_object_name = 'team_list'
    template_name = 'management/team/team_list.html'


class BuyerListView(ListView):
    model = Buyer
    context_object_name = 'buyer_list'
    template_name = 'management/buyer/buyer_list.html'


class DeviceTypeListView(ListView):
    model = DeviceType
    context_object_name = 'devicetype_list'
    template_name = 'management/device/devicetype_list.html'


# Detail Views
class UserDetailView(DetailView):
    model = User
    context_object_name = 'user_detail'
    template_name = 'management/user/user_detail.html'


class DeviceDetailView(DetailView):
    model = Device
    context_object_name = 'device_detail'
    template_name = 'management/device/device_detail.html'


# Search Views
class SearchResultsView(ListView):
    model = Device
    template_name = 'management/device/device_list.html'
    context_object_name = 'device_list'

    def get_queryset(self):  # новый
        query = self.request.GET.get('q')
        object_list = Device.objects.filter(
            Q(device_name__icontains=query) | Q(device_name__icontains=query)
        )
        return object_list

templates/management/device/device_create.html
{% extends 'management/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
Device create
{% endblock %}

{% block body %}

    <div class="book py-5 bg-light">
    <div class="container">
    <form method="POST" enctype="multipart/form-data">
        <div class="card bg-light my-4 p-4 text-center">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-success">Добавить</button>
            <span>{{ error }}</span>
        </div>
    </form>
    </div>
    </div>
{% endblock %}

templates/management/device/device_detail.html
{% extends 'management/base.html' %}
{% block title %}{{ device_detail.device_type }}{% endblock %}
{% block body %}
{% if device_detail %}
    <div class="container">
    <div style="margin: auto;" class="col-5">
        <div class="card mb-4 shadow-sm">
            <h3 class="card-header">{{ device_detail.device_type }}</h3>
            <div class="card-body">
                <img style="display: block; margin: auto; width: 50%;" src="{{ MEDIA_URL }}{{ device_detail.device_photo.url }}" alt="Card image">
                <hr>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Device name: <br> {{ device_detail.device_name }}</li>
                    <li class="list-group-item">Item number: {{ device_detail.item_number }}</li>
                    <li class="list-group-item">Paid by: {{ device_detail.paid_by }}</li>
                    <li class="list-group-item">Price: {{ device_detail.price }}</li>
                    <li class="list-group-item">Team: {{ device_detail.team }}</li>
                    <li class="list-group-item">In use: {% for user in device_detail.is_busy %} {{ user }} {% endfor %}</li>
                </ul>
                <hr>
                <div class="card-body">
                    <li class="list-group-item"> <a href="{{ device_detail.configuration }}" class="card-link">Configuration link</a></li>
                </div>
            </div>
            <div class="btn-group">
                {% if perms.PersonnelManagement.change_projectemail %}
                <a type="button" class="btn btn-primary" href="{% url 'management:device_update' device_detail.item_number %}">Edit</a>
                {% endif %}
                {% if perms.PersonnelManagement.delete_invoicetype %}
                <a type="button" class="btn btn-primary" href="{% url 'management:device_delete' device_detail.item_number %}">Delete</a>
                {% endif %}
            </div>
            <div class="card-footer text-muted">
                {{ device_detail.purchase_date }}
            </div>
        </div>
    </div>
    </div>
{% endif %}
{% endblock %}

templates/management/device/device_list.html
{% extends 'management/base.html' %}
{% block body %}
    {% if device_list %}
    <div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for device in device_list %}
                <div style="margin:auto;" class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                    <div class="card mb-4 shadow-sm">
                        <h3 class="card-header">{{ device.device_type }}</h3>
                        <div class="card-body">
                            <img style="display: block; margin-left: auto; margin-right: auto; width: 50%;" src="{{ MEDIA_URL }}{{ device.device_photo.url }}" alt="Card image">
                            <hr>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Device name: <br> {{ device.device_name }}</li>
                                <li class="list-group-item">Item number: {{ device.item_number }}</li>
                                <li class="list-group-item">Paid by: {{ device.paid_by }}</li>
                                <li class="list-group-item">Price: {{ device.price }}</li>
                                <li class="list-group-item">Team: {{ device.team }}</li>
                                <li class="list-group-item">
                                {% if device.is_busy %}
                                    In use: {% for user in device.is_busy %} {{ user }} {% endfor %}
                                {% else %}
                                <p style="color: forestgreen; font-size: large">Free to use</p>
                                {% endif %}</li>
                            </ul>
                            <hr>
                            <div class="card-body">
                                <li class="list-group-item"> <a href="{{ device.configuration }}" class="card-link">Configuration link</a></li>
                            </div>
                        </div>
                        <div class="btn-group">
                            {% if perms.PersonnelManagement.change_projectemail %}
                            <a type="button" class="btn btn-primary" href="{% url 'management:device_update' device.item_number %}">Edit</a>
                            {% endif %}
                            {% if perms.PersonnelManagement.delete_invoicetype %}
                            <a type="button" class="btn btn-primary" href="{% url 'management:device_delete' device.item_number %}">Delete</a>
                            {% endif %}
                        </div>
                        <div class="card-footer text-muted">
                            {{ device.purchase_date }}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    </div>
    {% else %}
        <div class="container">
        <div class="bg-light my-4 p-4 text-center">
            {% if request.user.is_authenticated %}
            <p>List is empty. Push the button to create a device.</p>
            <a class="btn btn-success" style="color: black" href="{% url 'device-create' %}">Сreate device</a>
            {% else %}
            <p>List is empty.</p>
            {% endif %}
        </div>
        </div>
    {% endif %}
{% endblock %}

templates/management/device/devicetype_create.html
{% extends 'management/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
Device type create
{% endblock %}

{% block body %}

    <div class="book py-5 bg-light">
    <div class="container">
    <form method="POST">
        <div class="card bg-light my-4 p-4 text-center">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-success">Добавить</button>
            <span>{{ error }}</span>
        </div>
    </form>
    </div>
    </div>
{% endblock %}

templates/management/device/devicetype_list.html
{% extends 'management/base.html' %}
{% block body %}
{% if devicetype_list %}
    <div class="container">
    <div class="row">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Team name</th>
                    <th scope="col">Operations</th>
                </tr>
            </thead>
             <tbody>
            {% for devicetype in devicetype_list %}
                <tr class="table-primary">
                    <th scope="row">{{ devicetype.device_type }}</th>
                    <td><div class="btn-group">
                            {% if perms.PersonnelManagement.change_projectemail %}
                            <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'management:devicetype_update' devicetype.id %}">Edit</a>
                            {% endif %}
                            {% if perms.PersonnelManagement.delete_invoicetype %}
                            <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'management:devicetype_delete' devicetype.id %}">Delete</a>
                            {% endif %}
                        </div></td>
                </tr>
            {% endfor %}
             </tbody>
        </table>
        </div>
    </div>
{% else %}
    <div class="container">
    <div class="bg-light my-4 p-4 text-center">
        {% if request.user.is_authenticated %}
        <p>List is empty. Push the button to create a device type.</p>
        <a class="btn btn-success" style="color: black" href="{% url 'devicetype-create' %}">Сreate device type</a>
        {% else %}
        <p>List is empty.</p>
        {% endif %}
    </div>
    </div>
{% endif %}
{% endblock %}